# 端口
server:
  port: 80

# 数据源
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver # mysql5使用com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/pet_supplies?serverTimezone=UTC #数据仓库
      username: root # 账号
      password: root # 密码
  main:
    allow-circular-references: true
# mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      table-prefix: pet_        #设置表名通用前缀
      id-type: auto                #设置主键id字段的生成策略为参照数据库设定的策略
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 运行日志开启
    map-underscore-to-camel-case: true # 去掉下划线，按照驼峰命名法
  mapper-locations: classpath:/mapper/*.xml

# 配置文件地址
reggie:
  path: G://file//img//

# 取消禁止

