# 端口
server:
  port: 80

# 数据源
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver # mysql5使用com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/pet_supplies?serverTimezone=UTC #数据仓库
      username: root # 账号
      password: root # 密码
  main:
    allow-circular-references: true
#  # redis缓存
#  redis:
#    host: localhost
#    port: 6379
#  # 缓存设置
#  cache:
#    type: redis
#    redis:
#      #是否使用前缀
#      use-key-prefix: true
#      #  指定前缀
#      key-prefix: pet_
#      # 是否使用空值
#      cache-null-values: false
#      # 最大缓存时间
#      time-to-live: 100s

jetcache:
  # 统计数据
  statIntervalMinutes: 1
  # 设置远程
  remote:
    default:
      type: redis
      host: localhost
      port: 6379
      keyConvertor: fastjson
      valueEnable: java
      valueDecode: java
      poolConfig:
        # 最大连接数
        maxTotal: 500
    pet:
      type: redis
      host: localhost
      port: 6379
      keyConvertor: fastjson
      valueEnable: java
      valueDecode: java
      poolConfig:
        # 最大连接数
        maxTotal: 500
  # 设置本地
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
    pet:
      type: linkedhashmap
      keyConvertor: fastjson
# mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      table-prefix: pet_        #设置表名通用前缀
      id-type: auto                #设置主键id字段的生成策略为参照数据库设定的策略
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 运行日志开启
    map-underscore-to-camel-case: true # 去掉下划线，按照驼峰命名法
  mapper-locations: classpath:/mapper/*.xml

# 配置文件地址
reggie:
  path: G://file//img//

# 取消禁止

